name: md-gromacs
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - gromacs=2026.0=*mpi_openmpi_cuda*
  - openmpi
  - python>=3.10
  - numpy
  - matplotlib
  - mdtraj
  - nextflow>=23.04
  - pip
  - pip:
    - pdb2pqr>=3.6
    - gmx_MMPBSA
