# PyMOL publication figure — XP352-BEN  (t = 91.0 ns)
# Auto-generated by generate_pose_figures.py

load /home/eulalio/gromacs/MD-gromacs/poses/XP352-BEN/receptor.pdb, receptor
load /home/eulalio/gromacs/MD-gromacs/poses/XP352-BEN/ligand.pdb, ligand

bg_color white

# ── Receptor ──────────────────────────────────────────────────────────────
hide everything, receptor
show cartoon, receptor
color gray75, receptor
set cartoon_fancy_helices, 1
set cartoon_rect_length, 1.2
set cartoon_oval_length, 1.2

# ── Ligante ───────────────────────────────────────────────────────────────
hide everything, ligand
show sticks, ligand
util.cbac ligand          # cyan carbons, standard element colors
set stick_radius, 0.18, ligand
show spheres, ligand and name CA   # Cα apenas (para peptídeos)
set sphere_scale, 0.25, ligand and name CA

# ── Resíduos-chave do sítio (ProLIF top 0) ─────────────────────────
# (nenhum resíduo-chave disponível)
# ── H-bonds e contatos polares ────────────────────────────────────────────
distance hbonds, receptor, ligand, 3.5, mode=2
set dash_color, red
set dash_width, 2.5
set dash_gap, 0.35
set dash_radius, 0.06
hide labels, hbonds

# ── Superfície do sítio de ligação (transparente) ─────────────────────────
create pocket, byres receptor within 5 of ligand
show surface, pocket
color tv_blue, pocket
set transparency, 0.60, pocket

# ── Câmera e iluminação ────────────────────────────────────────────────────
orient ligand
zoom ligand, 10
rotate y, 15
rotate x, -10

set ray_shadows, 1
set ray_opaque_background, 1
set ray_trace_mode, 1
set antialias, 2
set ambient, 0.35
set direct, 0.65
set specular, 0.20

# ── Render ─────────────────────────────────────────────────────────────────
ray 2400, 1800
png /home/eulalio/gromacs/MD-gromacs/poses/XP352-BEN/pose.png, dpi=300, ray=1
quit
